language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
  - "pypy3"
install:
  # - pip3 install -r requirements.txt
  - python3 setup.py develop --user
script:
  - python3 -m unittest discover -s tests
