language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
  - "pypy3"
install:
  # - pip install -r requirements.txt
  - python setup.py install #develop --user  # Fails selectively for different versions.
script:
  - python -m unittest discover -s tests
